"""add column  age

Revision ID: 142b4eb0997a
Revises: dfe5c9fe127a
Create Date: 2023-06-09 22:19:48.115743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142b4eb0997a'
down_revision = 'dfe5c9fe127a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waiters', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waiters', 'age')
    # ### end Alembic commands ###
