"""Create TableReservation

Revision ID: efff92173b07
Revises: 142b4eb0997a
Create Date: 2023-06-10 22:55:58.441025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efff92173b07'
down_revision = '142b4eb0997a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tables',
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('start_armor', sa.TIMESTAMP(), nullable=True),
    sa.Column('end_armor', sa.TIMESTAMP(), nullable=True),
    sa.Column('waiter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['waiter'], ['waiters.waiter_id'], ),
    sa.PrimaryKeyConstraint('table_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tables')
    # ### end Alembic commands ###
